import { expect, test, type Page } from "@playwright/test";

async function ask(page: Page, text: string) {
  await page.getByRole("textbox", { name: "Ask Alexa by keyboard" }).fill(text);
  await page.getByRole("button", { name: "Send", exact: true }).click();
}

test("play all, control order, and enqueue a second delivered fixture on stream end", async ({ page }) => {
  await page.goto("./");
  const panel = page.getByTestId("now-playing");
  await ask(page, "play all my stories");
  await expect(panel).toHaveAttribute("data-story-id", "st_ignacio_the_snail");
  const firstSrc = await page.getByTestId("story-audio").getAttribute("src");
  if (!firstSrc) throw new Error("first fixture audio URL missing");
  await expect(await page.request.get(new URL(firstSrc, page.url()).href)).toBeOK();
  const firstArt = await page.getByTestId("now-playing-art").getAttribute("src");
  if (!firstArt) throw new Error("first fixture art URL missing");
  await expect(await page.request.get(new URL(firstArt, page.url()).href)).toBeOK();
  const firstToken = await panel.getAttribute("data-play-token");
  expect(firstToken).toBeTruthy();
  await expect(panel).toHaveAttribute("data-offset-ms", "0");
  await ask(page, "next story");
  await expect(panel).toHaveAttribute("data-story-id", "st_mauricio_the_bull");
  const secondSrc = await page.getByTestId("story-audio").getAttribute("src");
  if (!secondSrc) throw new Error("second fixture audio URL missing");
  expect(secondSrc).not.toBe(firstSrc);
  await expect(await page.request.get(new URL(secondSrc, page.url()).href)).toBeOK();
  expect(await panel.getAttribute("data-play-token")).not.toBe(firstToken);
  await ask(page, "previous story");
  await expect(panel).toHaveAttribute("data-story-id", "st_ignacio_the_snail");
  await ask(page, "restart this story");
  await expect(panel).toHaveAttribute("data-offset-ms", "0");
  await ask(page, "repeat this story");
  await expect(panel).toHaveAttribute("data-story-id", "st_ignacio_the_snail");
  await ask(page, "play all my stories");
  await page.getByTestId("story-audio").evaluate((audio) => audio.dispatchEvent(new Event("ended")));
  await expect(panel).toHaveAttribute("data-story-id", "st_mauricio_the_bull");
});

test("creator, title, newest, and missing delivery resolve against the fixture catalog", async ({ page }) => {
  await page.goto("./");
  const panel = page.getByTestId("now-playing");
  await ask(page, "play stories by Aunt Whitney");
  await expect(panel).toHaveAttribute("data-story-id", "st_ignacio_the_snail");
  await ask(page, "play Martina the music loving mermaid");
  await expect(panel).toHaveAttribute("data-story-id", "st_martina_the_mermaid");
  const martinaAudio = await page.getByTestId("story-audio").getAttribute("src");
  if (!martinaAudio) throw new Error("Martina fixture audio URL missing");
  await expect(await page.request.get(new URL(martinaAudio, page.url()).href)).toBeOK();
  await expect(page.getByTestId("now-playing-art")).toHaveJSProperty("naturalWidth", 480);
  await ask(page, "play my newest story");
  await expect(panel).toHaveAttribute("data-story-id", "st_mauricio_the_bull");
  await ask(page, "play The unseen dragon");
  await expect(page.getByLabel("Transcript")).toContainText("couldn't find that delivered story");
  await expect(panel).not.toHaveAttribute("data-story-id", /st_/);
});

test("draft, named-listener handoff, update, reaction, wish, occasion, help, and credits stay fixture-only", async ({ page }) => {
  await page.goto("./");
  const transcript = page.getByLabel("Transcript");
  await ask(page, "let's create a bedtime story");
  await expect(transcript).toContainText("What general theme");
  await ask(page, "about mermaids for Morgan");
  await expect(transcript).toContainText("Saved a name-free demo draft about mermaids");
  await expect(transcript.locator(".transcript-row.alexa")).not.toContainText("Morgan");
  await ask(page, "send it to Morgan");
  await expect(transcript).toContainText("choose the listener in Spoken Letter and finish delivery there");
  await ask(page, "create a story for Morgan");
  await expect(transcript).toContainText("choose the listener in Spoken Letter and finish delivery there");
  await ask(page, "read my latest draft");
  await expect(transcript).toContainText("latest saved demo draft is about mermaids");
  await expect(transcript).toContainText("A friendly mermaid finds a lost shell");
  await ask(page, "check demo notification");
  await expect(transcript).toContainText("offline simulator did not send a device notification");
  await expect(transcript).toContainText("fixture_new_mermaid_story");
  await ask(page, "what is new?");
  await expect(transcript).toContainText("Martina the music loving mermaid");
  await ask(page, "show my demo updates");
  await expect(transcript).toContainText("No unread demo updates");
  await ask(page, "play Martina the music loving mermaid");
  await page.getByTestId("story-audio").evaluate((audio) => audio.dispatchEvent(new Event("ended")));
  await ask(page, "open spoken letter");
  await expect(transcript).toContainText("Did you like or love that story?");
  await ask(page, "open spoken letter");
  await expect(transcript.locator(".transcript-row.alexa")).not.toContainText("Did you like or love that story?");
  await ask(page, "I love that story");
  await expect(transcript).toContainText("demo reaction was saved in this simulation");
  await ask(page, "read my demo reactions");
  await expect(transcript).toContainText("1 demo reaction receipt");
  await expect(transcript).toContainText("mock-reaction-1");
  await ask(page, "I want a story about mermaids");
  await expect(transcript).toContainText("Confirm a demo wish about mermaids");
  await ask(page, "yes");
  await expect(transcript).toContainText("demo wish about mermaids was saved in this simulation");
  await ask(page, "ask Aunt Whitney for another mermaid story");
  await expect(transcript).toContainText("Confirm a demo wish about mermaids with Aunt Whitney");
  await ask(page, "yes");
  await expect(transcript).toContainText("demo wish about mermaids with Aunt Whitney was saved in this simulation");
  await ask(page, "read my demo wishes");
  await expect(transcript).toContainText("2 demo wish receipts");
  await ask(page, "I want a story about forest");
  await expect(transcript).toContainText("Confirm a demo wish about forest");
  await ask(page, "play my stories");
  await expect(page.getByTestId("now-playing")).toHaveAttribute("data-story-id", "st_ignacio_the_snail");
  await ask(page, "yes");
  await expect(transcript.locator(".transcript-row.alexa")).not.toContainText("wish about forest was saved");
  await ask(page, "any family occasions?");
  await expect(transcript).toContainText("synthetic fixture");
  await ask(page, "how do I create a story?");
  await expect(transcript).toContainText("finish delivery there");
  await ask(page, "how do I add credits?");
  await expect(transcript).toContainText("Alexa cannot charge you or change credits");
});
